services:
  postgis:
    build: .
    container_name: zhpark
    env_file:
      - path: ./.env
    volumes:
      - db:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - "5411:5432"
    shm_size: '1gb'
volumes:
  db: