services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    container_name: zhpark-db
    env_file:
      - path: ./.env
    volumes:
      - db:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - "${POSTGRES_PORT}:5432"

  flask-api:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: zhpark-api
    environment:
      - POSTGRES_HOST=postgis
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./:/app
    depends_on:
      - postgis
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zhpark-frontend
    environment:
      - API_URL=http://63.34.88.109:5000
    volumes:
      - ./frontend:/usr/share/nginx/html
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask-api

volumes:
  db:zhpark-frontend  | 
zhpark-frontend  | 2025/02/26 20:50:12 [emerg] 10#10: cannot load certificate "/etc/letsencrypt/live/your-domain.com/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/your-domain.com/fullchain.pem, r) error:10000080:BIO routines::no such file)
zhpark-frontend  | nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/your-domain.com/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/your-domain.com/fullchain.pem, r) error:10000080:BIO routines::no such file)
zhpark-frontend  | nginx: configuration file /etc/nginx/nginx.conf test failed
zhpark-frontend  | 
zhpark-frontend  | The nginx plugin is not working; there may be problems with your existing configuration.
zhpark-frontend  | The error was: MisconfigurationError('Error while running nginx -c /etc/nginx/nginx.conf -t.\n\n2025/02/26 20:50:12 [emerg] 10#10: cannot load certificate "/etc/letsencrypt/live/your-domain.com/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/your-domain.com/fullchain.pem, r) error:10000080:BIO routines::no such file)\nnginx: [emerg] cannot load certificate "/etc/letsencrypt/live/your-domain.com/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/your-domain.com/fullchain.pem, r) error:10000080:BIO routines::no such file)\nnginx: configuration file /etc/nginx/nginx.conf test failed\n')
zhpark-frontend  | 2025/02/26 20:50:12 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/your-domain.com/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/your-domain.com/fullchain.pem, r) error:10000080:BIO routines::no such file)
zhpark-frontend  | nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/your-domain.com/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/your-domain.com/fullchain.pem, r) error:10000080:BIO routines::no such file)
zhpark-frontend exited with code 1

  letsencrypt: 