services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    container_name: zhpark-db
    env_file:
      - path: ./.env
    volumes:
      - db:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - "${POSTGRES_PORT}:5432"

  flask-api:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: zhpark-api
    environment:
      - POSTGRES_HOST=postgis
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./:/app
    depends_on:
      - postgis
    ports:
      - "5000:5000"
    restart: always  # Ensures the container restarts if it crashes
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: zhpark-frontend
    environment:
      - ENVIRONMENT=prod
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.prod.conf:/etc/nginx/conf.d/default.conf  # Mount nginx config
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask-api
    networks:
      - app-network

volumes:
  db:
  letsencrypt:

networks:
  app-network:
    driver: bridge
